sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LJv2Nd5OmH6/4W452L46Y4c9KDibEfgLjIYXBxbFRnbI6EzIB2ZPr6LD4wCveTZhoxD+38IcH90BzzW4jOxFJY1+4esJKbuH1YOvovOjt6ui8vI4jhVfSV3QApfgddeyo5N4y78Q03JYaDbpK3XW0AbxPG9NYt9vdDGYZgLgjkvELXWxnGZGbIAIX7nNOKGLO8w+ycuQRpHD6ygdcmF49ZUfEsxwD/KDOnxgHxzPA7MvxSIpKNQl2wE0brCVJX3XxUAMFjDWxvI8bwlRCxtAwpgiY3el4ud/ald5atOp1Lu3fhrY7aDb5JrDw4Qnc+1fojobuWo9x2xLXqk04BqQagWCq8f6oA7dM7sfl/dUIKSXrj4/XAQLyoLeClG0EnQ3IieYdqs44NV2FAcK4H/X4SAZn+fI8MWoK3SkyzdQmEEt+2zTY1cquqUQTbgAQSUl6fa5H66+iMt3hZzwcuSkyhETB27w/BrZxMwZZv8XHu8dOgTiuj6iOzHg1/d4p3cWEfj8T9QnTdGbi5WLGydme992qhB5FlzEnZvEX6u0dO+gaGZZWw/U7bg1B/D8fu/uOdPyAH+S9swg8sgLrfHdwJx2uD6SdRHPP5VIuVCTJcSA96L4mlFvePfAzRXM6/sfUxUq5wXjHMAZuA5L1ZG+72TTPTfqD1+w0kEEmQIu/tU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Quotations-from-the-Project-Gutenberg-Editions-of-the-Works-of-Charles-Dudley-Warner_3471
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy